sudo: required
dist: trusty

language: haxe

os:
  - linux
#  - osx

# you can specify futher versions as found at http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - development
  
# see https://github.com/back2dos/travix/issues/10#issuecomment-343126503
env:
  - HAXE_TARGET=interp
  - HAXE_TARGET=neko
  - HAXE_TARGET=python
  - HAXE_TARGET=node
  - HAXE_TARGET=js
  - HAXE_TARGET=flash
  - HAXE_TARGET=java
  - HAXE_TARGET=cpp
  - HAXE_TARGET=cs
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  - HAXE_TARGET=lua
  - HAXE_TARGET=hl
  
matrix:
  fast_finish: true
  allow_failures:
   # - haxe: development
    - env: HAXE_TARGET=flash   # see https://github.com/travis-ci/travis-ci/issues/8481
    - env: HAXE_TARGET=lua     
    - env: HAXE_TARGET=hl     
  exclude:
   # - haxe: development
   # - os: osx
    
install:
  # hxPako must be installed from git
  - haxelib git hxPako https://github.com/azrafe7/hxPako.git
  - haxelib install travix
  # to always use the latest version of travix comment out the previous line and uncomment the next
  # - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix $HAXE_TARGET
  # force usage of hxPako for both Compress/Uncompress
  - haxelib run travix $HAXE_TARGET -D PAKOFILL_HXPAKO
